### ISSUE TITLE
feat: Support change directories with option `--dir.*`

### ISSUE THREAD

**Issue by tingtt** [tingtt/systemd-cd#19]
# Issues

- Support change directories with option `--dir.*`
  - Currently, pipeline execution fails after directory change

# To-Do

- [x] Remove unsupported options
- [ ] Support to change directories with option `--dir.*`
  - [ ] Move files if directory changed
  - [ ] Or run pipeline with correct directories
  - [ ] Switch them with option (e.g. `bool` type option `--dir.move`)
